import { ChangeEventHandler } from 'react';
type Color = 'default' | 'green' | 'red';
type Size = 'sm' | 'default' | 'lg';
type Props = {
    id?: string;
    label?: string;
    error?: string;
    size?: Size;
    color?: Color;
    name?: string;
    value?: string;
    type?: string;
    onChange?: ChangeEventHandler<HTMLInputElement>;
    className?: string;
    expanded?: boolean;
    disabled?: boolean;
    spellCheck?: boolean;
    min?: number;
    max?: number;
};
export declare const Input: ({ id, label, error, color, size, type, name, value, min, max, onChange, className, expanded, disabled, spellCheck, }: Props) => import("react/jsx-runtime").JSX.Element;
export {};
