import { ChangeEventHandler } from 'react';
import { ControlSize } from '../types';
type Color = 'default' | 'green' | 'red';
export type TextAreaProps = {
    id?: string;
    label?: string;
    error?: string;
    size?: ControlSize;
    color?: Color;
    name?: string;
    value?: string;
    onChange?: ChangeEventHandler<HTMLTextAreaElement>;
    className?: string;
    expanded?: boolean;
    disabled?: boolean;
    spellCheck?: boolean;
    rows?: number;
    cols?: number;
};
export declare const TextArea: ({ id, label, error, color, size, name, value, onChange, className, expanded, disabled, spellCheck, rows, cols, }: TextAreaProps) => import("react/jsx-runtime").JSX.Element;
export {};
